#pragma once

/*
Enum of all the Tiles in the game.
*/

namespace Game {
    // Enum of all possible tiles for our tilemap.
    enum Tiles {
        Empty,
        Wall_Top_Left,
        Wall_Top_Mid,
        Wall_Top_Right,
        Wall_Left,
        Wall_Mid,
        Wall_Right,
        Wall_Fountain_Top,
        Wall_Fountain_Mid_Red,
        Wall_Fountain_Mid_Blue,
        Wall_Fountain_Bot_Red,
        Wall_Fountain_Bot_Blue,
        Wall_Hole_A,
        Wall_Hole_B,
        Wall_Banner_Red,
        Wall_Banner_Blue,
        Wall_Banner_Green,
        Wall_Banner_Yellow,
        Column_Top,
        Column_Mid,
        Column_Base,
        Wall_Column_Top,
        Wall_Column_Mid,
        Wall_Column_Bot,
        Wall_Goo,
        Wall_Goo_Base,
        Floor,
        Floor_A,
        Floor_B,
        Floor_C,
        Floor_D,
        Floor_E,
        Floor_F,
        Floor_G,
        Floor_H,
        Floor_Ladder,
        Floor_Spikes,
        Wall_Side_Top_Left,
        Wall_Side_Top_Right,
        Wall_Side_Mid_Left,
        Wall_Side_Mid_Right,
        Wall_Side_Front_Left,
        Wall_Side_Front_Right,
        Wall_Corner_Top_Left,
        Wall_Corner_Top_Right,
        Wall_Corner_Left,
        Wall_Corner_Right,
        Wall_Corner_Bottom_Left,
        Wall_Corner_Bottom_Right,
        Wall_Corner_Front_Left,
        Wall_Corner_Front_Right,
        Wall_Inner_Corner_L_Top_Left,
        Wall_Inner_Corner_L_Top_Right,
        Wall_Inner_Corner_Mid_Left,
        Wall_Inner_Corner_Mid_Right,
        Wall_Inner_Corner_T_Top_Left,
        Wall_Inner_Corner_T_Top_Right,
        Edge,
        Hole,
        Door_Hole,
        Doors_Frame_Left,
        Doors_Frame_Top,
        Doors_Frame_Right,
    };
}